<?php
/**
 * Created by PhpStorm.
 * User: aliez
 * Date: 21/11/2017
 * Time: 16:54
 */
namespace app\admin\controller;

use think\Db;

class Article extends Common
{

    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function article()
    {
        $list = Db::name('article')->paginate(10);
        $this->assign('list',$list);
        return view();
    }
    public function addArticle()
    {
        if(request()->isPost())
        {

        }
        $cate = Db::name('category')->field('id,name,pid')->where(['is_cate'=>1,'pid'=>0])->select();
        $this->assign('cate',$cate);
        return view();
    }

    public function getCategory()
    {
        $cate = Db::name('category')->field('id,name,pid')->where(['is_cate' => 1])->select();
        return json($cate);
    }

    public function getChildCategory($pid)
    {
        $cate = Db::name('category')->field('id,name,pid')->where(['is_cate' => 1,'pid'=>$pid])->select();
        if($cate)
        {
            return ['code'=>1,'cate'=>$cate];
        }else{
            return ['code'=>0,'cate'=>''];
        }

    }

    //拼装数据
    public function getTree($arr,$pid=0)
    {
        $list = array();
        foreach ($arr as $key => $val)
        {
            if($val['pid'] == $pid){
                $list[] = $val;
                $list[$key][] = $this->getTree($arr,$val['id']);
            }
        }
        return $list;
    }
}