<?php
/**
 * Created by PhpStorm.
 * User: aliez
 * Date: 10/11/2017
 * Time: 15:48
 */
namespace app\admin\controller;

use think\Db;

class Product extends Common
{
    public function  _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //产品列表
    public function productList()
    {
        return view();
    }

    //添加产品
    public function productAdd()
    {
        return view();
    }
}