<?php
/**
 * Created by PhpStorm.
 * User: aliez
 * Date: 22/03/2018
 * Time: 17:34
 */

namespace app\admin\controller;

use think\Db;

class Upload extends Common
{
    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    // 文件上传
    public function index()
    {

    }


    public function upload(){
        // 获取上传文件
        $file = request()->file('upfile');
        $path = ROOT_PATH . 'public' . DS . 'uploads';
        $validate = ['size'=>10240,'ext'=>'jpg,png,gif'];
        // 移动到框架应用根目录/uploads/ 目录下
        $info = $file->validate($validate)->move($path);
        if($info){
            // 成功上传后 获取上传信息
            // 输出 jpg
            echo $info->getExtension();
            // 输出 20160820/42a79759f284b767dfcb2a0197904287.jpg
            echo $info->getSaveName();
            // 输出 42a79759f284b767dfcb2a0197904287.jpg
            echo $info->getFilename();
        }else{
            // 上传失败获取错误信息
            echo $file->getError();
        }
    }


}